server:
  port: 8080

spring:
  application:
    name: FILE-STORAGE
  datasource:
    url: jdbc:mysql://localhost:3306/FileStorage1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect




